M48
; DRILL file {KiCad 8.0.2} date 2024-08-04T20:07:18-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-04T20:07:18-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0550
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1250
%
G90
G05
T1
X3.858Y-4.2335
X4.2518Y-4.2335
T2
X3.6614Y-1.4744
X3.6614Y-2.9744
M30
