M48
; DRILL file {KiCad 7.0.7} date Mon Mar 18 21:13:53 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-18T21:13:53-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0550
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1250
%
G90
G05
T1
X3.858Y-4.2335
X4.2518Y-4.2335
T2
X3.6614Y-1.4744
X3.6614Y-2.9744
T0
M30
